# Generated by Django 4.2.1 on 2023-11-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_remove_cita_hora_aten_alter_cita_fecha_aten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.TextField(primary_key=True, serialize=False)),
                ('pnom_cli', models.TextField(max_length=20)),
                ('snom_cli', models.TextField(max_length=20)),
                ('appaterno_cli', models.TextField(max_length=20)),
                ('apmaterno_cli', models.TextField(max_length=20)),
                ('correo_cli', models.TextField(max_length=60)),
                ('telefono_cli', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_emp', models.TextField(primary_key=True, serialize=False)),
                ('pnom_emp', models.TextField(max_length=20)),
                ('snom_emp', models.TextField(max_length=20)),
                ('appaterno_emp', models.TextField(max_length=20)),
                ('apmaterno_emp', models.TextField(max_length=20)),
                ('cargo', models.TextField(max_length=40)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FaBo',
            fields=[
                ('num_fb', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('detalle_fb', models.TextField()),
                ('totalpagar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('cant_prod', models.IntegerField()),
                ('detalle_prod', models.TextField(max_length=400)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('pnom_prov', models.TextField(max_length=20)),
                ('snom_prov', models.TextField(max_length=20)),
                ('appaterno_prov', models.TextField(max_length=20)),
                ('apmaterno_prov', models.TextField(max_length=20)),
                ('rubro', models.TextField(max_length=40)),
                ('correo_prov', models.TextField(max_length=60)),
                ('telefono_prov', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='id',
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_cita',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.TextField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.TextField(max_length=20)),
                ('modelo', models.TextField(max_length=30)),
                ('año', models.IntegerField()),
                ('km', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.TextField(max_length=50)),
                ('desc_serv', models.TextField(max_length=400)),
                ('costo_serv', models.IntegerField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('desc_prod', models.TextField(max_length=400)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.proveedor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='num_fb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.fabo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cliente'),
        ),
    ]
