# Generated by Django 4.2.1 on 2023-11-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_cliente_empleado_fabo_pedido_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='id_cita',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apmaterno_cli',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='appaterno_cli',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_cli',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pnom_cli',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut_cli',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='snom_cli',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apmaterno_emp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='appaterno_emp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pnom_emp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut_emp',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='snom_emp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apmaterno_prov',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='appaterno_prov',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_prov',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pnom_prov',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='snom_prov',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_serv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
