# Generated by Django 4.1.5 on 2023-11-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_alter_cita_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='num_fb',
        ),
        migrations.AddField(
            model_name='fabo',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.cita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_aten',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
