# Generated by Django 4.2.1 on 2023-11-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_alter_cita_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apmaterno_emp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='snom_emp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
