# Generated by Django 4.2.1 on 2023-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_alter_empleado_apmaterno_emp_alter_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apmaterno_cli',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_cli',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='snom_cli',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cli',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
