# Generated by Django 4.2.1 on 2023-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_alter_cliente_apmaterno_cli_alter_cliente_correo_cli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cli',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut_emp',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
