# Generated by Django 4.2.1 on 2023-11-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_remove_producto_orden_pedido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='detalle_prod',
        ),
    ]
