# Generated by Django 4.2.1 on 2023-11-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_remove_pedido_detalle_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='desc_cita',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(to='taller.servicio'),
        ),
    ]
