# Generated by Django 4.2.7 on 2023-11-23 15:50

from django.db import migrations, models
import taller.models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_remove_cita_desc_cita_cita_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.CharField(choices=[('1', '08:00 am'), ('2', '09:00 am'), ('3', '10:00 am'), ('4', '11:00 am'), ('5', '12:00 am'), ('6', '01:00 pm'), ('7', '02:00 pm'), ('8', '03:00 pm'), ('9', '04:00 pm')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_aten',
            field=models.DateField(help_text='(Día-Mes-Año)', validators=[taller.models.validar_dia]),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('horario', 'fecha_aten')},
        ),
    ]
