# Generated by Django 4.2.2 on 2023-11-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_cita_horario_alter_cita_fecha_aten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabo',
            name='medio',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta de débito'), ('3', 'Tarjeta de credito'), ('4', 'Fiado')], default='1', max_length=30),
        ),
        migrations.RemoveField(
            model_name='fabo',
            name='detalle_fb',
        ),
        migrations.AddField(
            model_name='fabo',
            name='detalle_fb',
            field=models.ManyToManyField(to='taller.servicio'),
        ),
    ]
