# Generated by Django 4.2.2 on 2023-11-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0015_fabo_medio_remove_fabo_detalle_fb_fabo_detalle_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabo',
            name='detalle_fb',
            field=models.ManyToManyField(blank=True, null=True, to='taller.servicio'),
        ),
        migrations.AlterField(
            model_name='fabo',
            name='medio',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta de débito'), ('3', 'Tarjeta de crédito'), ('4', 'Fiado')], default='1', max_length=30),
        ),
    ]
